//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.12 at 09:06:00 PM CST 
//


package com.safeway.cgct.objects;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.jtan010.cgct package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.jtan010.cgct
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Calcgroup }
     * 
     */
    public Calcgroup createCalcgroup() {
        return new Calcgroup();
    }

    /**
     * Create an instance of {@link Calcgroup.Rule }
     * 
     */
    public Rule createCalcgroupRule() {
        return new Rule();
    }

    /**
     * Create an instance of {@link Calcgroup.Rule.Conditionset }
     * 
     */
    public Conditionset createCalcgroupRuleConditionset() {
        return new Conditionset();
    }

    /**
     * Create an instance of {@link Calcgroup.Rule.Conditionset.Parameter }
     * 
     */
    public Parameter createCalcgroupRuleConditionsetParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link Calcgroup.Rule.Conditionset.Condition }
     * 
     */
    public Condition createCalcgroupRuleConditionsetCondition() {
        return new Condition();
    }

}
